### ISSUE TITLE
Help.. 🥹

### ISSUE THREAD

**Issue by gmzii** [lucetre/gh-probot#4]
github 너무 어렵습니다. 도와주세여.

**Comment by lucetre** [comment]
ㅎㅇ gmzii

**Comment by lucetre** [comment]
![image](https://github.com/lucetre/gh-probot/assets/26702243/8763d6ee-6811-46a6-9a9d-ad29d41c26f5)

**Comment by gmzii** [comment]
이거 거의 방명록 가튼데

**Comment by lucetre** [comment]
클로즈 해봐요

**Comment by lucetre** [comment]
리오픈

**Comment by lucetre** [comment]
저 봇 만들고 있는중
